import type { PageDefinition } from "./types";

/** Registro de páginas editables desde el panel (estilo WordPress). */
export const PAGE_DEFINITIONS: PageDefinition[] = [
  {
    slug: "home",
    title: "Home",
    publicPath: "/",
    description: "Header, banner con video y textos principales.",
    fields: [
      {
        key: "header.logoText",
        label: "Texto del logo",
        type: "text",
        section: "Header (cabecera)",
        fallback: "TOP RENTALS",
      },
      {
        key: "header.link1Label",
        label: "Enlace 1 — texto",
        type: "text",
        section: "Header (cabecera)",
        fallback: "Propiedades",
      },
      {
        key: "header.link1Href",
        label: "Enlace 1 — URL",
        type: "url",
        section: "Header (cabecera)",
        fallback: "/propiedades",
      },
      {
        key: "header.link2Label",
        label: "Enlace 2 — texto",
        type: "text",
        section: "Header (cabecera)",
        fallback: "Corporativo",
      },
      {
        key: "header.link2Href",
        label: "Enlace 2 — URL",
        type: "url",
        section: "Header (cabecera)",
        fallback: "/corporate",
      },
      {
        key: "header.link3Label",
        label: "Enlace 3 — texto",
        type: "text",
        section: "Header (cabecera)",
        fallback: "Club Top Rentals",
      },
      {
        key: "header.link3Href",
        label: "Enlace 3 — URL",
        type: "url",
        section: "Header (cabecera)",
        fallback: "#",
      },
      {
        key: "header.ctaLabel",
        label: "Botón header — texto",
        type: "text",
        section: "Header (cabecera)",
        fallback: "Reservar ahora",
      },
      {
        key: "header.ctaHref",
        label: "Botón header — URL",
        type: "url",
        section: "Header (cabecera)",
        fallback: "/propiedades",
      },
      {
        key: "hero.title",
        label: "Título principal (H1)",
        type: "text",
        section: "Banner principal (video)",
        required: true,
        fallback: "Departamentos con servicio de hotel.",
        hint: "Tipografía Inter Bold 68px en el diseño.",
      },
      {
        key: "hero.subtitle",
        label: "Subtítulo",
        type: "textarea",
        section: "Banner principal (video)",
        fallback: "Alquileres temporarios en 15 torres\nBuenos Aires · Quito.",
        hint: "Podés usar Enter para una segunda línea.",
      },
      {
        key: "hero.videoSrc",
        label: "Video del banner (archivo MP4)",
        type: "video",
        section: "Banner principal (video)",
        hint: "Subí un MP4. Tiene prioridad sobre la URL externa.",
      },
      {
        key: "hero.videoUrl",
        label: "Video del banner (URL externa)",
        type: "url",
        section: "Banner principal (video)",
        hint: "Opcional si ya subiste archivo. Ej: https://…/hero.mp4",
      },
      {
        key: "hero.posterSrc",
        label: "Imagen de respaldo (poster)",
        type: "image",
        section: "Banner principal (video)",
        fallback: "/images/placeholders/home-hero.svg",
        hint: "Se muestra mientras carga el video o si no hay video.",
      },
      {
        key: "hero.playingLabel",
        label: "Etiqueta video en reproducción",
        type: "text",
        section: "Banner principal (video)",
        fallback: "Reproduciendo",
      },
      {
        key: "hero.videoPlaceholder",
        label: "Texto placeholder (sin video)",
        type: "text",
        section: "Banner principal (video)",
        fallback:
          "[ Video: edificios, amenidades, lifestyle — loop · sin sonido ]",
      },
      {
        key: "hero.exploreLabel",
        label: "Texto scroll / explorar",
        type: "text",
        section: "Banner principal (video)",
        fallback: "Explorar",
      },
      {
        key: "hero.slideDurationSec",
        label: "Duración por slide (segundos)",
        type: "text",
        section: "Banner — carrusel",
        fallback: "8",
        hint: "Para los slides del JSON heroSlides en home-content.json. Edición avanzada del array en el archivo por ahora.",
      },
      {
        key: "hero.ctaPrimary",
        label: "Botón principal — texto",
        type: "text",
        section: "Banner principal (video)",
        fallback: "Reservar ahora",
      },
      {
        key: "hero.ctaPrimaryHref",
        label: "Botón principal — URL",
        type: "url",
        section: "Banner principal (video)",
        fallback: "/propiedades",
      },
      {
        key: "hero.ctaSecondary",
        label: "Botón secundario — texto",
        type: "text",
        section: "Banner principal (video)",
        fallback: "Soluciones corporativas",
      },
      {
        key: "hero.ctaSecondaryHref",
        label: "Botón secundario — URL",
        type: "url",
        section: "Banner principal (video)",
        fallback: "/corporate",
      },
      {
        key: "hero.whatsappUrl",
        label: "WhatsApp — URL",
        type: "url",
        section: "Banner principal (video)",
        fallback: "https://wa.me/",
        hint: "Enlace completo de WhatsApp.",
      },
      {
        key: "hero.whatsappEnabled",
        label: "Mostrar botón WhatsApp",
        type: "boolean",
        section: "Banner principal (video)",
        fallback: "true",
      },
      {
        key: "stats.label1",
        label: "Estadística 1 — número",
        type: "text",
        section: "Números",
        fallback: "+100",
      },
      {
        key: "stats.text1",
        label: "Estadística 1 — texto",
        type: "text",
        section: "Números",
        fallback: "Departamentos",
      },
      {
        key: "stats.label2",
        label: "Estadística 2 — número",
        type: "text",
        section: "Números",
        fallback: "+600",
      },
      {
        key: "stats.text2",
        label: "Estadística 2 — texto",
        type: "text",
        section: "Números",
        fallback: "Huéspedes al año",
      },
      {
        key: "stats.label3",
        label: "Estadística 3 — número",
        type: "text",
        section: "Números",
        fallback: "10",
      },
      {
        key: "stats.text3",
        label: "Estadística 3 — texto",
        type: "text",
        section: "Números",
        fallback: "Años de experiencia",
      },
      {
        key: "featured.title",
        label: "Título sección destacados",
        type: "text",
        section: "Propiedades destacadas",
        fallback: "Propiedades Destacadas",
      },
      {
        key: "buildings.title",
        label: "Título edificios",
        type: "text",
        section: "Edificios",
        fallback: "Nuestros edificios, por adentro.",
      },
      {
        key: "seo.title",
        label: "Título SEO",
        type: "text",
        section: "SEO",
        fallback: "Top Rentals — Alquiler temporario",
      },
      {
        key: "seo.description",
        label: "Descripción SEO",
        type: "textarea",
        section: "SEO",
        fallback: "Alquileres temporarios en Buenos Aires y Quito.",
      },
    ],
  },
  {
    slug: "nosotros",
    title: "Nosotros",
    publicPath: "/nosotros",
    description: "Quiénes somos, misión y contenido institucional.",
    fields: [
      {
        key: "hero.title",
        label: "Título de página",
        type: "text",
        section: "Cabecera",
        required: true,
        fallback: "Nosotros",
      },
      {
        key: "hero.subtitle",
        label: "Bajada",
        type: "textarea",
        section: "Cabecera",
      },
      {
        key: "hero.imageSrc",
        label: "Imagen de cabecera",
        type: "image",
        section: "Cabecera",
        fallback: "/images/placeholders/page-hero.svg",
      },
      {
        key: "body.intro",
        label: "Texto principal",
        type: "textarea",
        section: "Contenido",
      },
      {
        key: "body.column1",
        label: "Columna / bloque 1",
        type: "textarea",
        section: "Contenido",
      },
      {
        key: "body.column2",
        label: "Columna / bloque 2",
        type: "textarea",
        section: "Contenido",
      },
    ],
  },
  {
    slug: "corporate",
    title: "Corporate",
    publicPath: "/corporate",
    fields: [
      {
        key: "hero.title",
        label: "Título",
        type: "text",
        section: "Cabecera",
        fallback: "Soluciones corporativas",
      },
      {
        key: "hero.subtitle",
        label: "Subtítulo",
        type: "textarea",
        section: "Cabecera",
      },
      {
        key: "hero.imageSrc",
        label: "Imagen de cabecera",
        type: "image",
        section: "Cabecera",
        fallback: "/images/placeholders/page-hero.svg",
      },
      {
        key: "body.content",
        label: "Contenido",
        type: "textarea",
        section: "Contenido",
      },
    ],
  },
  {
    slug: "propiedades",
    title: "Propiedades",
    publicPath: "/propiedades",
    description: "Cabecera del listado; el motor GNAHS va aparte.",
    fields: [
      {
        key: "hero.title",
        label: "Título del listado",
        type: "text",
        section: "Cabecera",
        fallback: "Propiedades",
      },
      {
        key: "hero.subtitle",
        label: "Subtítulo",
        type: "textarea",
        section: "Cabecera",
      },
      {
        key: "hero.imageSrc",
        label: "Imagen de cabecera",
        type: "image",
        section: "Cabecera",
        fallback: "/images/placeholders/page-hero.svg",
      },
    ],
  },
  {
    slug: "propietarios",
    title: "Propietarios",
    publicPath: "/propietarios",
    fields: [
      {
        key: "hero.title",
        label: "Título",
        type: "text",
        section: "Cabecera",
        fallback: "¿Tenés una propiedad?",
      },
      {
        key: "hero.subtitle",
        label: "Subtítulo",
        type: "textarea",
        section: "Cabecera",
      },
      {
        key: "hero.imageSrc",
        label: "Imagen",
        type: "image",
        section: "Cabecera",
        fallback: "/images/placeholders/page-hero.svg",
      },
      {
        key: "body.content",
        label: "Contenido",
        type: "textarea",
        section: "Contenido",
      },
    ],
  },
  {
    slug: "real-estate",
    title: "Real Estate",
    publicPath: "/real-estate",
    fields: [
      {
        key: "hero.title",
        label: "Título",
        type: "text",
        section: "Cabecera",
        fallback: "Real Estate",
      },
      {
        key: "hero.imageSrc",
        label: "Imagen de cabecera",
        type: "image",
        section: "Cabecera",
        fallback: "/images/placeholders/page-hero.svg",
      },
      {
        key: "body.content",
        label: "Contenido",
        type: "textarea",
        section: "Contenido",
      },
    ],
  },
];

export function getPageDefinition(slug: string): PageDefinition | undefined {
  return PAGE_DEFINITIONS.find((p) => p.slug === slug);
}

export function getPageSlugs(): string[] {
  return PAGE_DEFINITIONS.map((p) => p.slug);
}
