import type { PageDefinition } from "./types";

/** Registro de páginas editables desde el panel (estilo WordPress). */
export const PAGE_DEFINITIONS: PageDefinition[] = [
  {
    slug: "home-header",
    title: "Header",
    publicPath: "/",
    description: "Cabecera del sitio: logo, menú y botón de reserva.",
    fields: [
      {
        key: "header.logoText",
        label: "Texto del logo",
        type: "text",
        section: "Cabecera",
        fallback: "TOP RENTALS",
      },
      {
        key: "header.link1Label",
        label: "Enlace 1 — texto",
        type: "text",
        section: "Cabecera",
        fallback: "Propiedades",
      },
      {
        key: "header.link1Href",
        label: "Enlace 1 — URL",
        type: "url",
        section: "Cabecera",
        fallback: "/propiedades",
      },
      {
        key: "header.link2Label",
        label: "Enlace 2 — texto",
        type: "text",
        section: "Cabecera",
        fallback: "Corporativo",
      },
      {
        key: "header.link2Href",
        label: "Enlace 2 — URL",
        type: "url",
        section: "Cabecera",
        fallback: "/corporate",
      },
      {
        key: "header.link3Label",
        label: "Enlace 3 — texto",
        type: "text",
        section: "Cabecera",
        fallback: "Club Top Rentals",
      },
      {
        key: "header.link3Href",
        label: "Enlace 3 — URL",
        type: "url",
        section: "Cabecera",
        fallback: "#",
      },
      {
        key: "header.link4Label",
        label: "Enlace 4 — texto",
        type: "text",
        section: "Cabecera",
        fallback: "Quiénes somos",
      },
      {
        key: "header.link4Href",
        label: "Enlace 4 — URL",
        type: "url",
        section: "Cabecera",
        fallback: "/nosotros",
      },
      {
        key: "header.link5Label",
        label: "Enlace 5 — texto",
        type: "text",
        section: "Cabecera",
        fallback: "Trabajá con nosotros",
      },
      {
        key: "header.link5Href",
        label: "Enlace 5 — URL",
        type: "url",
        section: "Cabecera",
        fallback: "/trabaja-con-nosotros",
      },
      {
        key: "header.ctaLabel",
        label: "Botón header — texto",
        type: "text",
        section: "Cabecera",
        fallback: "Reservar ahora",
      },
      {
        key: "header.ctaHref",
        label: "Botón header — URL",
        type: "url",
        section: "Cabecera",
        fallback: "/propiedades",
      },
    ],
  },
  {
    slug: "home",
    title: "Home",
    publicPath: "/",
    description: "Banner, secciones de la página de inicio y SEO.",
    fields: [
      {
        key: "hero.title",
        label: "Título principal (H1)",
        type: "text",
        section: "Banner principal (video)",
        required: true,
        fallback: "Departamentos con servicio de hotel.",
        hint: "Tipografía Inter Bold 68px en el diseño.",
      },
      {
        key: "hero.subtitle",
        label: "Subtítulo",
        type: "textarea",
        section: "Banner principal (video)",
        fallback: "Alquileres temporarios en 15 torres\nBuenos Aires · Quito.",
        hint: "Podés usar Enter para una segunda línea.",
      },
      {
        key: "hero.videoSrc",
        label: "Video del banner (archivo MP4)",
        type: "video",
        section: "Banner principal (video)",
        hint: "Subí un MP4. Tiene prioridad sobre la URL externa.",
      },
      {
        key: "hero.videoUrl",
        label: "Video del banner (URL externa)",
        type: "url",
        section: "Banner principal (video)",
        hint: "Opcional si ya subiste archivo. Ej: https://…/hero.mp4",
      },
      {
        key: "hero.posterSrc",
        label: "Imagen de respaldo (poster)",
        type: "image",
        section: "Banner principal (video)",
        fallback: "/images/placeholders/home-hero.svg",
        hint: "Se muestra mientras carga el video o si no hay video.",
      },
      {
        key: "hero.playingLabel",
        label: "Etiqueta video en reproducción",
        type: "text",
        section: "Banner principal (video)",
        fallback: "Reproduciendo",
      },
      {
        key: "hero.videoPlaceholder",
        label: "Texto placeholder (sin video)",
        type: "text",
        section: "Banner principal (video)",
        fallback:
          "[ Video: edificios, amenidades, lifestyle — loop · sin sonido ]",
      },
      {
        key: "hero.exploreLabel",
        label: "Texto scroll / explorar",
        type: "text",
        section: "Banner principal (video)",
        fallback: "Explorar",
      },
      {
        key: "hero.slideDurationSec",
        label: "Duración por slide (segundos)",
        type: "text",
        section: "Banner — carrusel",
        fallback: "8",
        hint: "Para los slides del JSON heroSlides en home-content.json. Edición avanzada del array en el archivo por ahora.",
      },
      {
        key: "hero.ctaPrimary",
        label: "Botón principal — texto",
        type: "text",
        section: "Banner principal (video)",
        fallback: "Reservar ahora",
      },
      {
        key: "hero.ctaPrimaryHref",
        label: "Botón principal — URL",
        type: "url",
        section: "Banner principal (video)",
        fallback: "/propiedades",
      },
      {
        key: "hero.ctaSecondary",
        label: "Botón secundario — texto",
        type: "text",
        section: "Banner principal (video)",
        fallback: "Soluciones corporativas",
      },
      {
        key: "hero.ctaSecondaryHref",
        label: "Botón secundario — URL",
        type: "url",
        section: "Banner principal (video)",
        fallback: "/corporate",
      },
      {
        key: "hero.whatsappUrl",
        label: "WhatsApp — URL",
        type: "url",
        section: "Banner principal (video)",
        fallback: "https://wa.me/",
        hint: "Enlace completo de WhatsApp.",
      },
      {
        key: "hero.whatsappEnabled",
        label: "Mostrar botón WhatsApp",
        type: "boolean",
        section: "Banner principal (video)",
        fallback: "true",
      },
      {
        key: "stats.label1",
        label: "Estadística 1 — número",
        type: "text",
        section: "Debajo del buscador — Números",
        fallback: "+100",
      },
      {
        key: "stats.text1",
        label: "Estadística 1 — texto",
        type: "text",
        section: "Debajo del buscador — Números",
        fallback: "Personas en el equipo",
      },
      {
        key: "stats.label2",
        label: "Estadística 2 — número",
        type: "text",
        section: "Debajo del buscador — Números",
        fallback: "+100",
      },
      {
        key: "stats.text2",
        label: "Estadística 2 — texto",
        type: "text",
        section: "Debajo del buscador — Números",
        fallback: "Departamentos en operación",
      },
      {
        key: "stats.label3",
        label: "Estadística 3 — número",
        type: "text",
        section: "Debajo del buscador — Números",
        fallback: "+600",
      },
      {
        key: "stats.text3",
        label: "Estadística 3 — texto",
        type: "text",
        section: "Debajo del buscador — Números",
        fallback: "empresas alojadas por año",
      },
      {
        key: "stats.label4",
        label: "Estadística 4 — número",
        type: "text",
        section: "Debajo del buscador — Números",
        fallback: "10",
      },
      {
        key: "stats.text4",
        label: "Estadística 4 — texto",
        type: "text",
        section: "Debajo del buscador — Números",
        fallback: "años de operación",
      },
      {
        key: "differentials.title",
        label: "Título diferenciales",
        type: "text",
        section: "Debajo del buscador — Diferenciales",
        fallback: "Nuestros diferenciales",
      },
      {
        key: "differentials.card1Title",
        label: "Diferencial 1 — título",
        type: "text",
        section: "Debajo del buscador — Diferenciales",
        fallback: "Limpieza profesional",
      },
      {
        key: "differentials.card1Text",
        label: "Diferencial 1 — texto",
        type: "text",
        section: "Debajo del buscador — Diferenciales",
        fallback: "Estándares de hotel en cada departamento",
      },
      {
        key: "differentials.card2Title",
        label: "Diferencial 2 — título",
        type: "text",
        section: "Debajo del buscador — Diferenciales",
        fallback: "Propuesta estandarizada",
      },
      {
        key: "differentials.card2Text",
        label: "Diferencial 2 — texto",
        type: "text",
        section: "Debajo del buscador — Diferenciales",
        fallback: "Calidad consistente en cada propiedad",
      },
      {
        key: "differentials.card3Title",
        label: "Diferencial 3 — título",
        type: "text",
        section: "Debajo del buscador — Diferenciales",
        fallback: "Ubicaciones estratégicas",
      },
      {
        key: "differentials.card3Text",
        label: "Diferencial 3 — texto",
        type: "text",
        section: "Debajo del buscador — Diferenciales",
        fallback: "Edificios completos en zonas clave",
      },
      {
        key: "featured.title",
        label: "Título propiedades",
        type: "text",
        section: "Debajo del buscador — Propiedades",
        fallback: "Propiedades",
      },
      {
        key: "featured.linkLabel",
        label: "Enlace ver todas",
        type: "text",
        section: "Debajo del buscador — Propiedades",
        fallback: "Ver todas →",
      },
      {
        key: "featured.linkHref",
        label: "URL ver todas",
        type: "url",
        section: "Debajo del buscador — Propiedades",
        fallback: "/propiedades",
      },
      {
        key: "buildings.title",
        label: "Título",
        type: "text",
        section: "Video edificios",
        fallback: "Nuestros edificios, por adentro.",
      },
      {
        key: "buildings.subtitle",
        label: "Subtítulo",
        type: "textarea",
        section: "Video edificios",
        fallback:
          "Un recorrido por los departamentos, amenities y el estilo de vida Top Rentals.",
      },
      {
        key: "buildings.videoSrc",
        label: "Video — ruta local",
        type: "text",
        section: "Video edificios",
        fallback: "",
        hint: "Ej. /uploads/tour.mp4. Si está vacío, se muestra placeholder.",
      },
      {
        key: "buildings.videoUrl",
        label: "Video — URL externa",
        type: "url",
        section: "Video edificios",
        fallback: "",
      },
      {
        key: "buildings.posterSrc",
        label: "Imagen de portada del video",
        type: "text",
        section: "Video edificios",
        fallback: "",
      },
      {
        key: "buildings.meta",
        label: "Texto bajo el video",
        type: "text",
        section: "Video edificios",
        fallback: "2:45 min · Buenos Aires · Quito",
      },
      {
        key: "corporateTeaser.title",
        label: "Título",
        type: "textarea",
        section: "Bloque corporativo (home)",
        fallback: "Soluciones de alojamiento\npara empresas",
        hint: "Usá Enter para forzar un salto de línea en el título.",
      },
      {
        key: "corporateTeaser.description",
        label: "Descripción",
        type: "textarea",
        section: "Bloque corporativo (home)",
        fallback:
          "Coordinamos el alojamiento de tu equipo con la eficiencia y el profesionalismo que tu empresa necesita.",
      },
      {
        key: "corporateTeaser.bullet1",
        label: "Beneficio 1",
        type: "text",
        section: "Bloque corporativo (home)",
        fallback: "Múltiples departamentos en una misma torre",
      },
      {
        key: "corporateTeaser.bullet2",
        label: "Beneficio 2",
        type: "text",
        section: "Bloque corporativo (home)",
        fallback: "Contratos flexibles para estadías largas",
      },
      {
        key: "corporateTeaser.bullet3",
        label: "Beneficio 3",
        type: "text",
        section: "Bloque corporativo (home)",
        fallback: "Tarifas corporativas negociadas",
      },
      {
        key: "corporateTeaser.ctaLabel",
        label: "Botón — texto",
        type: "text",
        section: "Bloque corporativo (home)",
        fallback: "Cotizar alojamiento corporativo →",
      },
      {
        key: "corporateTeaser.ctaHref",
        label: "Botón — URL",
        type: "url",
        section: "Bloque corporativo (home)",
        fallback: "/corporate",
      },
      {
        key: "corporateTeaser.imageSrc",
        label: "Imagen lateral",
        type: "text",
        section: "Bloque corporativo (home)",
        fallback: "",
        hint: "Ruta en /public o /uploads.",
      },
      {
        key: "directBenefits.title",
        label: "Título sección",
        type: "text",
        section: "Beneficios directos",
        fallback: "Beneficios de reservar directo con nosotros",
      },
      {
        key: "directBenefits.card1Title",
        label: "Tarjeta 1 — título",
        type: "text",
        section: "Beneficios directos",
        fallback: "Mejor tarifa garantizada",
      },
      {
        key: "directBenefits.card1Text",
        label: "Tarjeta 1 — texto",
        type: "textarea",
        section: "Beneficios directos",
        fallback: "Beneficios exclusivos para socios. Siempre el precio más bajo.",
      },
      {
        key: "directBenefits.card2Title",
        label: "Tarjeta 2 — título",
        type: "text",
        section: "Beneficios directos",
        fallback: "Late check-out disponible",
      },
      {
        key: "directBenefits.card2Text",
        label: "Tarjeta 2 — texto",
        type: "textarea",
        section: "Beneficios directos",
        fallback: "Sujeto a disponibilidad, sin costo adicional.",
      },
      {
        key: "directBenefits.card3Title",
        label: "Tarjeta 3 — título",
        type: "text",
        section: "Beneficios directos",
        fallback: "Atención 24 hs",
      },
      {
        key: "directBenefits.card3Text",
        label: "Tarjeta 3 — texto",
        type: "textarea",
        section: "Beneficios directos",
        fallback: "Nuestro equipo siempre a tu disposición.",
      },
      {
        key: "directBenefits.card4Title",
        label: "Tarjeta 4 — título",
        type: "text",
        section: "Beneficios directos",
        fallback: "Confirmación inmediata",
      },
      {
        key: "directBenefits.card4Text",
        label: "Tarjeta 4 — texto",
        type: "textarea",
        section: "Beneficios directos",
        fallback: "Sin esperas ni aprobaciones de terceros.",
      },
      {
        key: "locations.title",
        label: "Título",
        type: "text",
        section: "Dónde operamos",
        fallback: "Dónde operamos",
      },
      {
        key: "locations.card1Title",
        label: "Buenos Aires — título",
        type: "text",
        section: "Dónde operamos",
        fallback: "Buenos Aires",
      },
      {
        key: "locations.card1Subtitle",
        label: "Buenos Aires — subtítulo",
        type: "text",
        section: "Dónde operamos",
        fallback: "+400 departamentos · 7 zonas",
      },
      {
        key: "locations.card1Href",
        label: "Buenos Aires — URL",
        type: "url",
        section: "Dónde operamos",
        fallback: "/propiedades",
      },
      {
        key: "locations.card2Title",
        label: "Quito — título",
        type: "text",
        section: "Dónde operamos",
        fallback: "Quito, Ecuador",
      },
      {
        key: "locations.card2Subtitle",
        label: "Quito — subtítulo",
        type: "text",
        section: "Dónde operamos",
        fallback: "+100 departamentos · La Carolina",
      },
      {
        key: "locations.card2Href",
        label: "Quito — URL",
        type: "url",
        section: "Dónde operamos",
        fallback: "/propiedades",
      },
      {
        key: "investorCta.title",
        label: "Título",
        type: "text",
        section: "Desarrolladores / Inversores",
        fallback: "¿Sos un desarrollador o querés invertir en el sector?",
      },
      {
        key: "investorCta.devLabel",
        label: "Botón desarrolladores",
        type: "text",
        section: "Desarrolladores / Inversores",
        fallback: "Desarrolladores →",
      },
      {
        key: "investorCta.devHref",
        label: "URL desarrolladores",
        type: "url",
        section: "Desarrolladores / Inversores",
        fallback: "/desarrolladores",
      },
      {
        key: "investorCta.invLabel",
        label: "Botón inversores",
        type: "text",
        section: "Desarrolladores / Inversores",
        fallback: "Inversores →",
      },
      {
        key: "investorCta.invHref",
        label: "URL inversores",
        type: "url",
        section: "Desarrolladores / Inversores",
        fallback: "/inversores",
      },
      {
        key: "seo.title",
        label: "Título SEO",
        type: "text",
        section: "SEO",
        fallback: "Top Rentals — Alquiler temporario",
      },
      {
        key: "seo.description",
        label: "Descripción SEO",
        type: "textarea",
        section: "SEO",
        fallback: "Alquileres temporarios en Buenos Aires y Quito.",
      },
    ],
  },
  {
    slug: "home-footer",
    title: "Footer",
    publicPath: "/",
    description: "Pie de página: marca, enlaces y redes sociales.",
    fields: [
      {
        key: "footer.brand",
        label: "Marca",
        type: "text",
        section: "Pie de página",
        fallback: "TOP RENTALS",
      },
      {
        key: "footer.tagline",
        label: "Tagline",
        type: "text",
        section: "Pie de página",
        fallback: "Temporary Apartments · Buenos Aires · Quito",
      },
      {
        key: "footer.siteUrl",
        label: "URL del sitio (texto)",
        type: "text",
        section: "Pie de página",
        fallback: "toprentals.com.ar",
      },
      {
        key: "footer.copyright",
        label: "Copyright",
        type: "text",
        section: "Pie de página",
        fallback: "© 2025 Top Rentals. Todos los derechos reservados.",
      },
      {
        key: "footer.link1Label",
        label: "Enlace 1 — texto",
        type: "text",
        section: "Enlaces",
        fallback: "Propiedades",
      },
      {
        key: "footer.link1Href",
        label: "Enlace 1 — URL",
        type: "url",
        section: "Enlaces",
        fallback: "/propiedades",
      },
      {
        key: "footer.link2Label",
        label: "Enlace 2 — texto",
        type: "text",
        section: "Enlaces",
        fallback: "Corporativo",
      },
      {
        key: "footer.link2Href",
        label: "Enlace 2 — URL",
        type: "url",
        section: "Enlaces",
        fallback: "/corporate",
      },
      {
        key: "footer.link3Label",
        label: "Enlace 3 — texto",
        type: "text",
        section: "Enlaces",
        fallback: "Club Top Rentals",
      },
      {
        key: "footer.link3Href",
        label: "Enlace 3 — URL",
        type: "url",
        section: "Enlaces",
        fallback: "/club-top-rentals",
      },
      {
        key: "footer.link4Label",
        label: "Enlace 4 — texto",
        type: "text",
        section: "Enlaces",
        fallback: "Propietarios",
      },
      {
        key: "footer.link4Href",
        label: "Enlace 4 — URL",
        type: "url",
        section: "Enlaces",
        fallback: "/propietarios",
      },
      {
        key: "footer.link5Label",
        label: "Enlace 5 — texto",
        type: "text",
        section: "Enlaces",
        fallback: "Real Estate",
      },
      {
        key: "footer.link5Href",
        label: "Enlace 5 — URL",
        type: "url",
        section: "Enlaces",
        fallback: "/real-estate",
      },
      {
        key: "footer.instagramUrl",
        label: "Instagram URL",
        type: "url",
        section: "Redes sociales",
        fallback: "https://instagram.com/",
      },
      {
        key: "footer.facebookUrl",
        label: "Facebook URL",
        type: "url",
        section: "Redes sociales",
        fallback: "https://facebook.com/",
      },
      {
        key: "footer.whatsappUrl",
        label: "WhatsApp URL",
        type: "url",
        section: "Redes sociales",
        fallback: "https://wa.me/",
      },
    ],
  },
  {
    slug: "trabaja",
    title: "Trabajá con nosotros",
    publicPath: "/trabaja-con-nosotros",
    description: "Carreras: hero, beneficios, posiciones y postulación espontánea.",
    fields: [
      {
        key: "hero.title",
        label: "Título hero",
        type: "text",
        section: "Hero",
        fallback: "Trabajá con nosotros",
      },
      {
        key: "hero.subtitle",
        label: "Subtítulo hero",
        type: "textarea",
        section: "Hero",
        fallback:
          "Somos un equipo apasionado por la hospitalidad y la innovación.",
      },
      {
        key: "hero.metaLine",
        label: "Línea meta (ciudades / modalidad)",
        type: "text",
        section: "Hero",
        fallback: "Buenos Aires · Quito · Tiempo completo y part-time",
      },
      {
        key: "why.title",
        label: "Título — Por qué trabajar",
        type: "text",
        section: "Beneficios",
        fallback: "¿Por qué trabajar en Top Rentals?",
      },
      {
        key: "positions.title",
        label: "Título — Posiciones",
        type: "text",
        section: "Posiciones",
        fallback: "Posiciones abiertas",
      },
      {
        key: "spontaneous.title",
        label: "Título — Postulación espontánea",
        type: "text",
        section: "Formulario",
        fallback: "¿No encontrás tu posición?",
      },
      {
        key: "spontaneous.subtitle",
        label: "Subtítulo — Formulario",
        type: "textarea",
        section: "Formulario",
        fallback:
          "Envianos tu CV y te tendremos en cuenta para futuras posiciones.",
      },
    ],
  },
  {
    slug: "nosotros",
    title: "Nosotros",
    publicPath: "/nosotros",
    description: "Quiénes somos: hero, historia, valores.",
    fields: [
      {
        key: "hero.title",
        label: "Título hero",
        type: "text",
        section: "Quiénes somos",
        fallback: "Quiénes somos",
      },
      {
        key: "hero.ctaLabel",
        label: "CTA — Ver propiedades",
        type: "text",
        section: "Quiénes somos",
        fallback: "Ver propiedades →",
      },
      {
        key: "history.title",
        label: "Título — Historia",
        type: "text",
        section: "Nuestra historia",
        fallback: "Nuestra historia",
      },
      {
        key: "history.imageSrc",
        label: "Imagen — Historia",
        type: "image",
        section: "Nuestra historia",
        fallback: "/images/properties/placeholder-lobby.png",
      },
      {
        key: "values.title",
        label: "Título — Valores",
        type: "text",
        section: "Valores",
        fallback: "Nuestros valores",
      },
    ],
  },
  {
    slug: "corporate",
    title: "Corporate",
    publicPath: "/corporate",
    description: "Landing corporativa: hero, beneficios, destinos y formulario de acceso.",
    fields: [
      {
        key: "hero.label",
        label: "Etiqueta hero",
        type: "text",
        section: "Hero",
        fallback: "CORPORATIVO",
      },
      {
        key: "hero.title",
        label: "Título hero",
        type: "text",
        section: "Hero",
        fallback: "Alojamiento corporativo sin complicaciones.",
      },
      {
        key: "hero.subtitle",
        label: "Subtítulo hero",
        type: "textarea",
        section: "Hero",
        fallback:
          "Soluciones de alojamiento profesional para empresas, equipos en movimiento y proyectos flexibles.",
      },
      {
        key: "hero.ctaPrimaryLabel",
        label: "CTA principal — texto",
        type: "text",
        section: "Hero",
        fallback: "Acceso corporativo →",
      },
      {
        key: "hero.ctaPrimaryHref",
        label: "CTA principal — URL",
        type: "url",
        section: "Hero",
        fallback: "#acceso-corporativo",
      },
      {
        key: "hero.ctaSecondaryLabel",
        label: "CTA secundario — texto",
        type: "text",
        section: "Hero",
        fallback: "Cotizar alojamiento →",
      },
      {
        key: "hero.ctaSecondaryHref",
        label: "CTA secundario — URL",
        type: "url",
        section: "Hero",
        fallback: "#acceso-corporativo",
      },
      {
        key: "hero.imageSrc",
        label: "Imagen de fondo hero",
        type: "image",
        section: "Hero",
        fallback: "/images/corporate/corporate-teaser.png",
      },
      {
        key: "designedFor.title",
        label: "Título — Diseñado para",
        type: "text",
        section: "Audiencia",
        fallback: "Diseñado para equipos que viajan",
      },
      {
        key: "features.title",
        label: "Título — Más que un departamento",
        type: "text",
        section: "Características",
        fallback: "Más que un departamento",
      },
      {
        key: "benefits.title",
        label: "Título — Beneficios",
        type: "text",
        section: "Beneficios",
        fallback: "Beneficios exclusivos para empresas",
      },
      {
        key: "howItWorks.title",
        label: "Título — Cómo funciona",
        type: "text",
        section: "Proceso",
        fallback: "Cómo funciona Top Rentals Corporate",
      },
      {
        key: "spaces.title",
        label: "Título — Espacios",
        type: "text",
        section: "Espacios",
        fallback: "Espacios para reuniones y eventos corporativos",
      },
      {
        key: "spaces.subtitle",
        label: "Subtítulo — Espacios",
        type: "textarea",
        section: "Espacios",
        fallback:
          "Soluciones flexibles para encuentros profesionales, reuniones privadas y eventos empresariales.",
      },
      {
        key: "destinations.title",
        label: "Título — Destinos",
        type: "text",
        section: "Destinos",
        fallback: "Destinos disponibles",
      },
      {
        key: "access.title",
        label: "Título — Acceso corporativo",
        type: "text",
        section: "Acceso y formulario",
        fallback: "Acceso Corporativo",
      },
      {
        key: "access.formTitle",
        label: "Título del formulario",
        type: "text",
        section: "Acceso y formulario",
        fallback: "Solicitar acceso corporate",
      },
    ],
  },
  {
    slug: "propiedades",
    title: "Propiedades",
    publicPath: "/propiedades",
    description: "Listado de departamentos, filtros y bloque en desarrollo.",
    fields: [
      {
        key: "hero.title",
        label: "Título del listado",
        type: "text",
        section: "Cabecera",
        fallback: "Nuestros departamentos",
      },
      {
        key: "hero.subtitle",
        label: "Subtítulo",
        type: "textarea",
        section: "Cabecera",
        fallback:
          "Más de 500 departamentos operados en edificios estratégicamente ubicados.",
      },
      {
        key: "development.label",
        label: "Etiqueta en desarrollo",
        type: "text",
        section: "En desarrollo",
        fallback: "En desarrollo",
      },
      {
        key: "development.title",
        label: "Título proyecto",
        type: "text",
        section: "En desarrollo",
        fallback: "Top Rentals Maipú",
      },
      {
        key: "development.description",
        label: "Descripción",
        type: "textarea",
        section: "En desarrollo",
        fallback:
          "90 unidades en el centro de la ciudad. Amenities de primer nivel. Próximamente.",
      },
      {
        key: "development.ctaLabel",
        label: "Enlace — texto",
        type: "text",
        section: "En desarrollo",
        fallback: "Registrarme para recibir novedades →",
      },
      {
        key: "development.ctaHref",
        label: "Enlace — URL",
        type: "url",
        section: "En desarrollo",
        fallback: "#",
      },
    ],
  },
  {
    slug: "propietarios",
    title: "Propietarios",
    publicPath: "/propietarios",
    fields: [
      {
        key: "hero.title",
        label: "Título",
        type: "text",
        section: "Cabecera",
        fallback: "¿Tenés una propiedad?",
      },
      {
        key: "hero.subtitle",
        label: "Subtítulo",
        type: "textarea",
        section: "Cabecera",
      },
      {
        key: "hero.imageSrc",
        label: "Imagen",
        type: "image",
        section: "Cabecera",
        fallback: "/images/placeholders/page-hero.svg",
      },
      {
        key: "body.content",
        label: "Contenido",
        type: "textarea",
        section: "Contenido",
      },
    ],
  },
  {
    slug: "real-estate",
    title: "Real Estate",
    publicPath: "/real-estate",
    fields: [
      {
        key: "hero.title",
        label: "Título",
        type: "text",
        section: "Cabecera",
        fallback: "Real Estate",
      },
      {
        key: "hero.imageSrc",
        label: "Imagen de cabecera",
        type: "image",
        section: "Cabecera",
        fallback: "/images/placeholders/page-hero.svg",
      },
      {
        key: "body.content",
        label: "Contenido",
        type: "textarea",
        section: "Contenido",
      },
    ],
  },
];

export function getPageDefinition(slug: string): PageDefinition | undefined {
  return PAGE_DEFINITIONS.find((p) => p.slug === slug);
}

export function getPageSlugs(): string[] {
  return PAGE_DEFINITIONS.map((p) => p.slug);
}
